CURRENCIES = [
  { 
    code = "KUNA", 
    issuer = "rn5bAQZmZaeDddhKfEh1FqVNQv7pU4nkKe", 
    description = "$KUNA – nostalgična, bezvrijedna, nezaustavljiva!", 
    icon = "https://github.com/ProjektKovanica/kovanica-toml/raw/main/kuna-logo.png",
    website = "https://github.com/ProjektKovanica/kovanica-toml/raw/main/.well-known/xrp-ledger.toml"
  }
]

[DOCUMENTATION]
WHITEPAPER_HR = "https://github.com/ProjektKovanica/kovanica-toml/raw/main/kovanica-whitepaper-hr.pdf"
WHITEPAPER_EN = "https://github.com/ProjektKovanica/kovanica-toml/raw/main/kovanica-whitepaper-en.pdf"
TOKENOMICS_HR = "https://github.com/ProjektKovanica/kovanica-toml/raw/main/kuna-tokenomics-hr.pdf"
TOKENOMICS_EN = "https://github.com/ProjektKovanica/kovanica-toml/raw/main/kuna-tokenomics-en.pdf"

[PROJECT]
name = "Kovanica"
website = "https://github.com/ProjektKovanica"
description = "Kovanica je inicijativa koja u Hrvatskoj potiče širenje i popularizaciju XRP Ledgera (XRPL) kroz svakodnevne primjene i inovativna rješenja."
founder = "bettercall.dzuks"
founder_contact = "kovanicahr@proton.me"

[SOCIAL]
x = "@ProjektKovanica"
discord = "https://discord.gg/TbzS59haeV"
telegram = "https://t.me/kovanicahr"
github = "https://github.com/ProjektKovanica"

[ACCOUNTS]
support_account = "rPcGaKCVhu63vi2GQnso4bipeaL5Z7WZAu"
