[[ACCOUNTS]]
address = "rn5bAQZmZaeDddhKfEh1FqVNQv7pU4nkKe"
desc = "Issuer wallet za KUNA token"

[[CURRENCIES]]
code = "KUNA"
issuer = "rn5bAQZmZaeDddhKfEh1FqVNQv7pU4nkKe"
name = "Kovanica"
desc = "$KUNA – nostalgična, bezvrijedna, nezaustavljiva!"
icon = "https://github.com/ProjektKovanica/kovanica-toml/blob/main/kuna-logo.png"
website = "https://kovanica.net/"

[[PRINCIPALS]]
name = "Kovanica"
email = "antonio@kovanica.net"
telegram = "https://t.me/kovanicahr"
x = "@ProjektKovanica"
discord = "https://discord.gg/TbzS59haeV"
